/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan progress event stream (SSE) */
        get: operations["scan_events_api_scan_get"];
        put?: never;
        /** Trigger a library rescan */
        post: operations["trigger_scan_api_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan Error Log
         * @description Skipped files from the last scan — path + reason.
         */
        get: operations["scan_error_log_api_scan_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracks */
        get: operations["list_tracks_api_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Track */
        get: operations["get_track_api_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Track */
        patch: operations["patch_track_api_tracks__track_id__patch"];
        trace?: never;
    };
    "/api/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Albums */
        get: operations["list_albums_api_albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Album */
        get: operations["get_album_api_albums__album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Album
         * @description Re-point the album's cover at an existing artwork row, or clear it.
         */
        patch: operations["update_album_api_albums__album_id__patch"];
        trace?: never;
    };
    "/api/artists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Artists */
        get: operations["list_artists_api_artists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{artist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist */
        get: operations["get_artist_api_artists__artist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Artist
         * @description Re-point the artist's portrait at an existing artwork row, or clear it.
         */
        patch: operations["update_artist_api_artists__artist_id__patch"];
        trace?: never;
    };
    "/api/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Genres
         * @description Genre browse list: grouped track tags with representative cover art.
         */
        get: operations["list_genres_api_genres_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/albums/{album_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Album Cover
         * @description Store an uploaded cover image, overriding the scan-derived artwork.
         */
        put: operations["set_album_cover_api_albums__album_id__cover_put"];
        post?: never;
        /**
         * Reset Album Cover
         * @description Clear the user-set cover — the scan-derived artwork takes back over.
         */
        delete: operations["reset_album_cover_api_albums__album_id__cover_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artists/{artist_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Artist Cover
         * @description Store an uploaded image as the artist's portrait, overriding the derived cover.
         */
        put: operations["set_artist_cover_api_artists__artist_id__cover_put"];
        post?: never;
        /**
         * Reset Artist Cover
         * @description Clear the user-set portrait — the derived artwork takes back over.
         */
        delete: operations["reset_artist_cover_api_artists__artist_id__cover_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Apply Tracks */
        post: operations["bulk_apply_tracks_api_tracks_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/bulk/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Undo */
        post: operations["bulk_undo_api_tracks_bulk_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder Tracks
         * @description Renumber the given tracks 1..n in the order listed (flagged user-edited, preserved on rescan).
         */
        post: operations["reorder_tracks_api_tracks_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder Favorites
         * @description Write the Favorites manual order; only currently loved tracks are placed.
         */
        post: operations["reorder_favorites_api_favorites_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Summary */
        get: operations["review_summary_api_review_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Playlists */
        get: operations["list_playlists_api_playlists_get"];
        put?: never;
        /** Create Playlist */
        post: operations["create_playlist_api_playlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playlist */
        get: operations["get_playlist_api_playlists__playlist_id__get"];
        put?: never;
        post?: never;
        /** Delete Playlist */
        delete: operations["delete_playlist_api_playlists__playlist_id__delete"];
        options?: never;
        head?: never;
        /** Update Playlist */
        patch: operations["update_playlist_api_playlists__playlist_id__patch"];
        trace?: never;
    };
    "/api/playlists/{playlist_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Playlist Cover
         * @description Store an uploaded cover image, overriding the 2×2 track mosaic.
         */
        put: operations["set_playlist_cover_api_playlists__playlist_id__cover_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Tracks
         * @description Append tracks, skipping ones already in it; counts go in X-Tracks-Added/Skipped headers.
         */
        post: operations["add_tracks_api_playlists__playlist_id__tracks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Track */
        delete: operations["remove_track_api_playlists__playlist_id__tracks__track_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{playlist_id}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Playlist */
        put: operations["reorder_playlist_api_playlists__playlist_id__order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stream/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Track */
        get: operations["stream_track_api_stream__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artwork/{artwork_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artwork */
        get: operations["get_artwork_api_artwork__artwork_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queue
         * @description The stored session, or an empty one when none exists (first run).
         */
        get: operations["get_queue_api_queue_get"];
        /**
         * Put Queue
         * @description The client's plan mirror: whole-snapshot replace with a client-built
         *     play order. A malformed order is a 422, never a corrupted server copy.
         */
        put: operations["put_queue_api_queue_put"];
        /**
         * Play Queue
         * @description Play this view: replace the queue with the whole filter and start at `start`.
         */
        post: operations["play_queue_api_queue_post"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Queue
         * @description The playhead update, plus a played_at stamp when a real playback
         *     start reports its track id — carried explicitly so an in-flight mirror
         *     PUT cannot mis-stamp.
         */
        patch: operations["patch_queue_api_queue_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlbumDetail */
        AlbumDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Artist */
            artist: string | null;
            /** Artist Id */
            artist_id: number | null;
            /** Year */
            year: number | null;
            /** Artwork Id */
            artwork_id: number | null;
            /** Track Count */
            track_count: number;
            /** Played At */
            played_at?: string | null;
            /** Cover Artwork Id */
            cover_artwork_id?: number | null;
            /** Duration Total */
            duration_total: number;
            /** Tracks */
            tracks: components["schemas"]["TrackOut"][];
        };
        /** AlbumListOut */
        AlbumListOut: {
            /** Items */
            items: components["schemas"]["AlbumSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** AlbumRef */
        AlbumRef: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Track Count */
            track_count: number;
        };
        /** AlbumSummary */
        AlbumSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Artist */
            artist: string | null;
            /** Artist Id */
            artist_id: number | null;
            /** Year */
            year: number | null;
            /** Artwork Id */
            artwork_id: number | null;
            /** Track Count */
            track_count: number;
            /** Played At */
            played_at?: string | null;
            /** Cover Artwork Id */
            cover_artwork_id?: number | null;
        };
        /** AlbumUpdate */
        AlbumUpdate: {
            /** Cover Artwork Id */
            cover_artwork_id?: number | null;
        };
        /** ArtistDetail */
        ArtistDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Album Count */
            album_count: number;
            /** Track Count */
            track_count: number;
            /** Artwork Id */
            artwork_id?: number | null;
            /** Cover Artwork Id */
            cover_artwork_id?: number | null;
            /** Albums */
            albums: components["schemas"]["AlbumSummary"][];
            /** Tracks */
            tracks: components["schemas"]["TrackOut"][];
        };
        /** ArtistListOut */
        ArtistListOut: {
            /** Items */
            items: components["schemas"]["ArtistSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ArtistSummary */
        ArtistSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Album Count */
            album_count: number;
            /** Track Count */
            track_count: number;
            /** Artwork Id */
            artwork_id?: number | null;
            /** Cover Artwork Id */
            cover_artwork_id?: number | null;
        };
        /** ArtistUpdate */
        ArtistUpdate: {
            /** Cover Artwork Id */
            cover_artwork_id?: number | null;
        };
        /** Body_set_album_cover_api_albums__album_id__cover_put */
        Body_set_album_cover_api_albums__album_id__cover_put: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_set_artist_cover_api_artists__artist_id__cover_put */
        Body_set_artist_cover_api_artists__artist_id__cover_put: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_set_playlist_cover_api_playlists__playlist_id__cover_put */
        Body_set_playlist_cover_api_playlists__playlist_id__cover_put: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * BulkApplyIn
         * @description Mass edit from the Organize view. Selection is either explicit
         *     `track_ids` or the same filter contract as GET /api/tracks minus
         *     pagination (`q` / `artist_id` / `album_id` / `review`, minus
         *     `except_ids`) — so a filter-wide apply touches exactly what the grid
         *     showed. A field absent from the JSON never touches the column; an
         *     explicit null clears the track number; empty artist/album strings clear
         *     the reference; 0 normalizes to null. `favorite` is intentionally not a
         *     bulk field.
         */
        BulkApplyIn: {
            /** Track Ids */
            track_ids?: number[] | null;
            /** Q */
            q?: string | null;
            /** Artist Id */
            artist_id?: number | null;
            /** Album Id */
            album_id?: number | null;
            /** Review */
            review?: string | null;
            /**
             * Except Ids
             * @default []
             */
            except_ids: number[];
            /** Title */
            title?: string | null;
            /** Artist */
            artist?: string | null;
            /** Album Artist */
            album_artist?: string | null;
            /** Album */
            album?: string | null;
            /** Track No */
            track_no?: number | null;
            /** Genre */
            genre?: string | null;
        };
        /** BulkApplyOut */
        BulkApplyOut: {
            /** Applied */
            applied: number;
        };
        /**
         * CollisionGroup
         * @description Albums whose titles collapse onto one normalized key: the scanner
         *     groups on exact strings, so suffix variants become siblings.
         */
        CollisionGroup: {
            /** Key */
            key: string;
            /** Albums */
            albums: components["schemas"]["AlbumRef"][];
        };
        /** GenreListOut */
        GenreListOut: {
            /** Items */
            items: components["schemas"]["GenreSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** GenreSummary */
        GenreSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Track Count */
            track_count: number;
            /** Album Count */
            album_count: number;
            /** Artwork Id */
            artwork_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibraryCounts */
        LibraryCounts: {
            /** Tracks */
            tracks: number;
            /** Albums */
            albums: number;
            /** Artists */
            artists: number;
            /** Playlists */
            playlists: number;
        };
        /** PlaylistCreate */
        PlaylistCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** PlaylistDetail */
        PlaylistDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Created At */
            created_at: string;
            /** Track Count */
            track_count: number;
            /** Duration Total */
            duration_total: number;
            /** Cover Artwork Id */
            cover_artwork_id: number | null;
            /** Artwork Ids */
            artwork_ids: number[];
            /** Tracks */
            tracks: components["schemas"]["PlaylistTrackOut"][];
        };
        /** PlaylistListOut */
        PlaylistListOut: {
            /** Items */
            items: components["schemas"]["PlaylistSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PlaylistOrderIn */
        PlaylistOrderIn: {
            /** Track Ids */
            track_ids: number[];
        };
        /** PlaylistSummary */
        PlaylistSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Created At */
            created_at: string;
            /** Track Count */
            track_count: number;
            /** Duration Total */
            duration_total: number;
            /** Cover Artwork Id */
            cover_artwork_id: number | null;
            /** Artwork Ids */
            artwork_ids: number[];
        };
        /** PlaylistTrackOut */
        PlaylistTrackOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Artist */
            artist: string | null;
            /** Artist Id */
            artist_id: number | null;
            /** Album */
            album: string | null;
            /** Album Id */
            album_id: number | null;
            /** Album Artist */
            album_artist?: string | null;
            /** Track No */
            track_no: number | null;
            /** Disc No */
            disc_no: number | null;
            /** Year */
            year: number | null;
            /** Duration */
            duration: number;
            /** Format */
            format: string;
            /** Favorite */
            favorite: boolean;
            /** Artwork Id */
            artwork_id: number | null;
            /** Path */
            path: string;
            /** Gain Db */
            gain_db?: number | null;
            /** Played At */
            played_at?: string | null;
            /** Genre */
            genre?: string | null;
            /** Added At */
            added_at?: string | null;
            /** Position */
            position: number;
        };
        /** PlaylistTracksIn */
        PlaylistTracksIn: {
            /** Track Ids */
            track_ids: number[];
        };
        /** PlaylistUpdate */
        PlaylistUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Cover Artwork Id */
            cover_artwork_id?: number | null;
        };
        /**
         * QueueOrigin
         * @description Where the queue came from — the "Playing from" sentence. `label` is
         *     the human name ("Album 03", "Everything, shuffled"); `href` is the route
         *     that makes the label a link. `manual` (a hand-built queue) carries no
         *     label — nothing renders.
         */
        QueueOrigin: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "album" | "artist" | "playlist" | "filter" | "shuffle-all" | "manual";
            /** Label */
            label?: string | null;
            /** Href */
            href?: string | null;
        };
        /**
         * QueuePatchIn
         * @description PATCH /api/queue — the playhead, on a 3 s throttle plus a pagehide
         *     flush. `played_track_id` rides the immediate start-of-play sync: when
         *     present, the server stamps tracks.played_at on THAT id — carried
         *     explicitly, never derived from the stored plan, so a mirror PUT still
         *     in flight cannot mis-stamp.
         */
        QueuePatchIn: {
            /** Order Pos */
            order_pos?: number | null;
            /** Position */
            position?: number | null;
            /** Played Track Id */
            played_track_id?: number | null;
        };
        /**
         * QueuePlayIn
         * @description POST /api/queue — "play this view". Exactly one of `track_ids` or
         *     the GET /api/tracks filter contract (minus pagination). The server
         *     resolves the WHOLE filter in one query — there is no page for the queue
         *     to be silently truncated to. `start` is the index into the resolved
         *     list that begins playback; `shuffle` builds the play order starting
         *     there instead. `origin` is the caller's declaration of what this view
         *     IS (the client knows; the server records it).
         */
        QueuePlayIn: {
            /** Track Ids */
            track_ids?: number[] | null;
            /** Q */
            q?: string | null;
            /** Artist Id */
            artist_id?: number | null;
            /** Album Id */
            album_id?: number | null;
            /** Review */
            review?: string | null;
            /** Favorite */
            favorite?: boolean | null;
            /** Genre Id */
            genre_id?: number | null;
            /**
             * Sort
             * @default title
             */
            sort: string;
            /**
             * Dir
             * @default asc
             */
            dir: string;
            /**
             * Start
             * @default 0
             */
            start: number;
            /**
             * Shuffle
             * @default false
             */
            shuffle: boolean;
            origin?: components["schemas"]["QueueOrigin"] | null;
        };
        /**
         * QueuePlayheadOut
         * @description PATCH's answer — tiny, because it rides the 3 s cadence.
         */
        QueuePlayheadOut: {
            /** Order Pos */
            order_pos: number;
            /** Position */
            position: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * QueuePutIn
         * @description PUT /api/queue — the client's plan mirror: the store remains the
         *     source of UI truth and PUTs its whole queue when the plan changes.
         *     `order` must be a permutation of 0..n-1 into `track_ids`. `origin`
         *     rides along unchanged — queue edits never rewrite where the queue came
         *     from.
         */
        QueuePutIn: {
            /** Track Ids */
            track_ids: number[];
            /** Order */
            order: number[];
            /** Order Pos */
            order_pos: number;
            /**
             * Position
             * @default 0
             */
            position: number;
            origin?: components["schemas"]["QueueOrigin"] | null;
        };
        /**
         * QueueSnapshot
         * @description The whole stored session — what GET /api/queue restores and what the
         *     play/replace endpoints echo back. `items` are the queue in insertion
         *     order; `order` is the play order as indexes into `items` (identity, or
         *     the shuffle plan); `order_pos` indexes `order` (-1 = built, nothing
         *     loaded); `position` is seconds into the current track. `origin` names
         *     what produced the queue — null for sessions that predate it. The client
         *     store adopts this shape verbatim.
         */
        QueueSnapshot: {
            /** Items */
            items: components["schemas"]["TrackOut"][];
            /** Order */
            order: number[];
            /** Order Pos */
            order_pos: number;
            /** Position */
            position: number;
            origin?: components["schemas"]["QueueOrigin"] | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * ReviewSummary
         * @description The "Needs attention" strip. Deterministic counts only — no fuzzy
         *     matching. `undo_available` rides along: the view needs both on load,
         *     and undo state lives server-side (one generation).
         */
        ReviewSummary: {
            /** No Album */
            no_album: number;
            /** Single Track Albums */
            single_track_albums: number;
            /** Mixed Album Artist Albums */
            mixed_album_artist_albums: number;
            /** Missing Track No */
            missing_track_no: number;
            /** Suffix Collisions */
            suffix_collisions: number;
            /** Collision Groups */
            collision_groups: components["schemas"]["CollisionGroup"][];
            /** Undo Available */
            undo_available: boolean;
        };
        /** ScanErrorEntry */
        ScanErrorEntry: {
            /** Path */
            path: string;
            /** Reason */
            reason: string;
        };
        /**
         * ScanErrorLog
         * @description Skipped files of the last scan, for Settings' disclosure.
         */
        ScanErrorLog: {
            /** Total */
            total: number;
            /** Truncated */
            truncated: boolean;
            /** Items */
            items: components["schemas"]["ScanErrorEntry"][];
        };
        /** ScanStatus */
        ScanStatus: {
            /**
             * State
             * @enum {string}
             */
            state: "idle" | "scanning";
            /** Phase */
            phase: ("scan" | "watch" | "analyze") | null;
            /** Current */
            current: number;
            /** Total */
            total: number;
            /** Errors */
            errors: number;
            /** Finished At */
            finished_at: string | null;
            /**
             * Mount Guard
             * @default false
             */
            mount_guard: boolean;
        };
        /** SearchOut */
        SearchOut: {
            /** Query */
            query: string;
            /** Tracks */
            tracks: components["schemas"]["TrackOut"][];
            /** Albums */
            albums: components["schemas"]["AlbumSummary"][];
            /** Artists */
            artists: components["schemas"]["ArtistSummary"][];
            /** Playlists */
            playlists: components["schemas"]["PlaylistSummary"][];
        };
        /** SettingsOut */
        SettingsOut: {
            /** Library Path */
            library_path: string;
            /** Library Exists */
            library_exists: boolean;
            scan: components["schemas"]["ScanStatus"];
            counts: components["schemas"]["LibraryCounts"];
        };
        /** TrackListOut */
        TrackListOut: {
            /** Items */
            items: components["schemas"]["TrackOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** TrackOut */
        TrackOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Artist */
            artist: string | null;
            /** Artist Id */
            artist_id: number | null;
            /** Album */
            album: string | null;
            /** Album Id */
            album_id: number | null;
            /** Album Artist */
            album_artist?: string | null;
            /** Track No */
            track_no: number | null;
            /** Disc No */
            disc_no: number | null;
            /** Year */
            year: number | null;
            /** Duration */
            duration: number;
            /** Format */
            format: string;
            /** Favorite */
            favorite: boolean;
            /** Artwork Id */
            artwork_id: number | null;
            /** Path */
            path: string;
            /** Gain Db */
            gain_db?: number | null;
            /** Played At */
            played_at?: string | null;
            /** Genre */
            genre?: string | null;
            /** Added At */
            added_at?: string | null;
        };
        /**
         * TrackPatch
         * @description Get Info / inline-rename payload.
         *
         *     artist/album are name strings — the editor find-or-creates rows. Only
         *     fields the client sends are applied; sent overlay fields set their
         *     `user_edited` bit so rescans preserve them. `album_artist` pins a
         *     compilation's identity (empty string clears it); `genre` replaces the
         *     track's tag genres with the one named (empty clears).
         */
        TrackPatch: {
            /** Title */
            title?: string | null;
            /** Artist */
            artist?: string | null;
            /** Album Artist */
            album_artist?: string | null;
            /** Album */
            album?: string | null;
            /** Track No */
            track_no?: number | null;
            /** Favorite */
            favorite?: boolean | null;
            /** Genre */
            genre?: string | null;
        };
        /**
         * TrackReorderIn
         * @description Organize drag-reorder: the album's tracks in their new order. Each
         *     track's number is rewritten to its position in the list (1..n) and
         *     flagged user-edited, so a rescan preserves it.
         */
        TrackReorderIn: {
            /** Track Ids */
            track_ids: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    scan_events_api_scan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_scan_api_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    scan_error_log_api_scan_errors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanErrorLog"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    list_tracks_api_tracks_get: {
        parameters: {
            query?: {
                q?: string | null;
                artist_id?: number | null;
                album_id?: number | null;
                review?: string | null;
                favorite?: boolean | null;
                genre_id?: number | null;
                sort?: string;
                dir?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_api_tracks__track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_track_api_tracks__track_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_albums_api_albums_get: {
        parameters: {
            query?: {
                q?: string | null;
                sort?: string;
                dir?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_album_api_albums__album_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_album_api_albums__album_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artists_api_artists_get: {
        parameters: {
            query?: {
                q?: string | null;
                sort?: string;
                dir?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artist_api_artists__artist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_artist_api_artists__artist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtistUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_genres_api_genres_get: {
        parameters: {
            query?: {
                q?: string | null;
                sort?: string;
                dir?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_album_cover_api_albums__album_id__cover_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_set_album_cover_api_albums__album_id__cover_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_album_cover_api_albums__album_id__cover_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_artist_cover_api_artists__artist_id__cover_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_set_artist_cover_api_artists__artist_id__cover_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_artist_cover_api_artists__artist_id__cover_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_apply_tracks_api_tracks_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkApplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkApplyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_undo_api_tracks_bulk_undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkApplyOut"];
                };
            };
        };
    };
    reorder_tracks_api_tracks_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackReorderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkApplyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_favorites_api_favorites_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackReorderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkApplyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_summary_api_review_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
        };
    };
    list_playlists_api_playlists_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_playlist_api_playlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playlist_api_playlists__playlist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_playlist_api_playlists__playlist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_playlist_api_playlists__playlist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_playlist_cover_api_playlists__playlist_id__cover_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_set_playlist_cover_api_playlists__playlist_id__cover_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tracks_api_playlists__playlist_id__tracks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistTracksIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_track_api_playlists__playlist_id__tracks__track_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_playlist_api_playlists__playlist_id__order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                playlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaylistOrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_track_api_stream__track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artwork_api_artwork__artwork_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artwork_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queue_api_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSnapshot"];
                };
            };
        };
    };
    put_queue_api_queue_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueuePutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    play_queue_api_queue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueuePlayIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_queue_api_queue_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueuePatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueuePlayheadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
